variable:
  tmp_folder: /tmp
  timestamp_layout_str: '{value}'
  timestamp_layout: '2006-01-02 15:04:05.000000'
  date_layout_str: '{value}'
  date_layout: '2006-01-02 15:04:05'
  error_filter_table_exists: already
  error_ignore_drop_table: NotFound
  quote_char: ''